# Comprehensive Hindi to English symptom mapping
HINDI_TO_ENGLISH_SYMPTOMS = {
    # Basic symptoms
    'बुखार': 'fever',
    'सिरदर्द': 'headache',
    'खांसी': 'cough',
    'सूखी खांसी': 'dry cough',
    'जुकाम': 'cold',
    'पेट दर्द': 'stomach pain',
    'शरीर दर्द': 'body ache',
    'मतली': 'nausea',
    'उल्टी': 'vomiting',
    'दस्त': 'diarrhea',
    'कब्ज': 'constipation',
    'अम्लता': 'acidity',
    'अपच': 'indigestion',
    
    # Oral and dental symptoms
    'गले में दर्द': 'sore throat',
    'सूखे होंठ': 'dry lips',
    'दांत दर्द': 'toothache',
    'गंभीर दांत दर्द': 'severe toothache',
    'मुंह में छाले': 'mouth sores',
    'दर्दनाक छाले': 'painful ulcers',
    'सूजे हुए मसूड़े': 'swollen gums',
    'लाल मसूड़े': 'red gums',
    'खून बहना': 'bleeding',
    'मसूड़ों से खून': 'bleeding gums',
    'सांसों में बदबू': 'bad breath',
    'निगलने में दर्द': 'pain swallowing',
    'निगलने में कठिनाई': 'difficulty swallowing',
    'मुंह में सफेद धब्बे': 'white patches in mouth',
    'जलन': 'burning sensation',
    'लालिमा': 'redness',
    'सूजन': 'swelling',
    'दरार': 'cracking',
    'संवेदनशीलता': 'sensitivity',
    'गर्म/ठंडे के प्रति संवेदनशीलता': 'sensitivity to hot/cold',
    'मसालेदार भोजन के प्रति संवेदनशीलता': 'sensitivity to spicy food',
    
    # Digestive symptoms
    'सीने में जलन': 'heartburn',
    'सीने में दर्द': 'chest pain',
    'पेट फूलना': 'bloating',
    'गैस': 'gas',
    'पेट में दर्द': 'abdominal pain',
    'भोजन के बाद जलन': 'burning pain after meals',
    'खट्टा स्वाद': 'sour taste',
    'उल्टी में खून': 'vomiting blood',
    'वजन कम होना': 'weight loss',
    'भूख न लगना': 'loss of appetite',
    'खाने में कठिनाई': 'difficulty eating',
    'चबाने में दर्द': 'pain on chewing',
    'चबाने में कठिनाई': 'difficulty chewing',
    'पतला मल': 'loose stools',
    'कठोर मल': 'hard stools',
    'मल त्याग में तनाव': 'straining',
    'मल त्याग में कठिनाई': 'difficulty in passing stools',
    'पेट में दर्द होना': 'stomach pain',
    'जी मिचलाना': 'feeling sick',
    
    # General symptoms
    'दर्द': 'pain',
    'तेज दर्द': 'severe pain',
    'धड़कता दर्द': 'throbbing pain',
    'चिड़चिड़ापन': 'irritability',
    'थकान': 'fatigue',
    'कमजोरी': 'weakness',
    'चिंता': 'anxiety',
    'अवसाद': 'depression',
    'अनिद्रा': 'insomnia',
    'नींद न आना': 'sleeplessness',
    'बेचैनी': 'restlessness',
    'चक्कर आना': 'dizziness',
    'भारीपन': 'heaviness',
    'प्रकाश के प्रति संवेदनशीलता': 'sensitivity to light',
    'तनाव': 'tension',
    'माइग्रेन': 'migraine',
    'तेज सिरदर्द': 'severe headache',
    'धड़कता दर्द': 'throbbing pain',
    'आंखों में दर्द': 'eye pain',
    'दृश्य समस्याएं': 'visual disturbances',
    'तेज बुखार': 'high temperature',
    'कंपकंपी': 'chills',
    'पसीना': 'sweating',
    'पानी की कमी': 'dehydration',
    'पेट में ऐंठन': 'abdominal cramps',
    'मांसपेशियों में अकड़न': 'muscle stiffness',
    'ऐंठन': 'spasms',
    'हिलने में कठिनाई': 'difficulty moving',
    'दर्द का फैलना': 'radiating pain',
    'घबराहट': 'nervousness',
    'तेज़ दिल की धड़कन': 'rapid heartbeat',
    'कांपना': 'trembling',
    'बार-बार मल त्याग': 'frequent bowel movements',
    'मुंह में खराबी': 'stomach discomfort',
    'उल्टी की इच्छा': 'urge to vomit',
    'पेट की समस्या': 'abdominal discomfort',
    
    # Respiratory symptoms
    'सांस लेने में तकलीफ': 'difficulty breathing',
    'सीने में जकड़न': 'chest tightness',
    'सीने में असुविधा': 'chest discomfort',
    'गीली खांसी': 'wet cough',
    'गले में खराश': 'throat irritation',
    'सीने में जमाव': 'chest congestion',
    'घरघराहट': 'wheezing',
    'नाक बहना': 'runny nose',
    'छींक आना': 'sneezing',
    'आंखों से पानी': 'watery eyes',
    'जुकाम होना': 'congestion',
    'बंद नाक': 'nasal congestion',
    
    # Skin and appearance
    'चकत्ते': 'rash',
    'खुजली': 'itching',
    'लाल धब्बे': 'red patches',
    'त्वचा की समस्याएं': 'skin problems',
    'मुंहासे': 'pimples',
    'फुंसी': 'acne',
    'तैलीय त्वचा': 'oily skin',
    'ब्लैकहेड्स': 'blackheads',
    'व्हाइटहेड्स': 'whiteheads',
    'सूजन': 'inflammation',
    'खरोंच': 'scratchiness',
    'कर्कशता': 'hoarseness',
    'ग्रंथियों में सूजन': 'swollen glands',
    
    # Other symptoms
    'बुखार तेज': 'high fever',
    'हल्का बुखार': 'mild fever',
    'रात में बढ़ना': 'night aggravation',
    'चेहरे पर सूजन': 'facial swelling',
    'मुंह खोलने में कठिनाई': 'difficulty opening mouth',
    'पस निकलना': 'pus discharge',
    'लार गिरना': 'drooling',
    'बार-बार संक्रमण': 'recurrent infections',
    'जीभ बड़ी होना': 'enlarged tongue',
    'बोलने में समस्या': 'speech issues',
    'वायुमार्ग में रुकावट': 'airway obstruction',
    'काले धब्बे दांतों पर': 'black spots on teeth',
    'गुहा': 'cavities',
    'दांत हिलना': 'tooth loosening',
    'मुलायम होना': 'tenderness',
    'स्वाद में बदलाव': 'change in taste',
    'खाते समय दर्द': 'pain while eating',
    'लार कम होना': 'reduced saliva',
    'लार ग्रंथि की पथरी': 'salivary gland stone',
    'लार ग्रंथि में सूजन': 'swollen salivary gland',
    'बार-बार छाले': 'recurrent sores',
    'लाल किनारा': 'red border',
    'दर्द होना': 'soreness',
    'काटने की प्रवृत्ति': 'biting tendency',
    'भोजन उल्टा आना': 'regurgitation',
    
    # Pain symptoms
    'कमर दर्द': 'back pain',
    'पीठ दर्द': 'back pain',
    'निचले कमर में दर्द': 'lower back pain',
    'जबड़े में दर्द': 'jaw pain',
    'जोड़ों का दर्द': 'joint pain',
    
    # Common phrases
    'खाँसी': 'cough',
    'सूखी खाँसी': 'dry cough',
    'गीली खाँसी': 'wet cough'
}

# English to Hindi for display
ENGLISH_TO_HINDI_SYMPTOMS = {v: k for k, v in HINDI_TO_ENGLISH_SYMPTOMS.items()}

def translate_hindi_to_english(hindi_symptom):
    """Translate a Hindi symptom to English"""
    hindi_symptom = hindi_symptom.strip()
    return HINDI_TO_ENGLISH_SYMPTOMS.get(hindi_symptom, hindi_symptom)

def translate_english_to_hindi(english_symptom):
    """Translate an English symptom to Hindi"""
    english_symptom = english_symptom.strip().lower()
    return ENGLISH_TO_HINDI_SYMPTOMS.get(english_symptom, english_symptom)

def translate_symptoms_list(symptoms_list):
    """
    Translate a list of symptoms from Hindi to English if needed.
    Returns list of English symptoms.
    """
    english_symptoms = []
    for symptom in symptoms_list:
        symptom = symptom.strip()
        # Check if symptom contains Hindi characters
        if any('\u0900' <= c <= '\u097F' for c in symptom):
            # Try to translate from Hindi
            english = translate_hindi_to_english(symptom)
            english_symptoms.append(english)
        else:
            # Already English
            english_symptoms.append(symptom)
    return english_symptoms

# Comprehensive English to Hindi translations for content
CONTENT_TRANSLATIONS = {
    # Common medicines and remedies
    'Turmeric milk': 'हल्दी दूध',
    'Ginger tea': 'अदरक की चाय',
    'turmeric milk': 'हल्दी दूध',
    'ginger tea': 'अदरक की चाय',
    'honey': 'शहद',
    'Honey': 'शहद',
    'warm water': 'गर्म पानी',
    'cold milk': 'ठंडा दूध',
    'saltwater': 'नमक का पानी',
    'salt water': 'नमक का पानी',
    'Salt water': 'नमक का पानी',
    'Peppermint oil': 'पुदीना तेल',
    'Aloe vera gel': 'एलोवेरा जेल',
    'Clove oil': 'लौंग का तेल',
    'Chamomile tea': 'कैमोमाइल चाय',
    'Willow bark tea': 'विलो छाल की चाय',
    'Coconut oil': 'नारियल तेल',
    'Carom seeds': 'अजवाइन',
    'Ajwain': 'अजवाइन',
    'Isabgol': 'इसबगोल',
    'Psyllium husk': 'इसबगोल',
    
    # Diseases
    'Cough': 'खांसी',
    'Common Cold': 'सामान्य सर्दी-जुकाम',
    'Sore Throat': 'गले में खराश',
    'Indigestion': 'अपच',
    'Acidity': 'एसिडिटी',
    'Headache': 'सिरदर्द',
    'Constipation': 'कब्ज',
    'Acne': 'मुँहासे',
    'Toothache': 'दांत दर्द',
    'Insomnia': 'अनिद्रा',
    'Fever': 'बुखार',
    'Diarrhea': 'दस्त',
    'Nausea': 'मतली',
    'Back Pain': 'कमर दर्द',
    'Anxiety': 'चिंता',
    'GERD': 'एसिड रिफ्लक्स',
    'GERD (Gastro-oesophageal reflux)': 'एसिड रिफ्लक्स (जीईआरडी)',
    'Gastritis': 'गैस्ट्राइटिस',
    'Gastritis (H. pylori)': 'गैस्ट्राइटिस (एच. पाइलोरी)',
    'Dental caries': 'दांतों में सड़न',
    'Gingivitis': 'मसूड़ों की सूजन',
    
    # Instructions and measurements
    'cup': 'कप',
    'cups': 'कप',
    'teaspoon': 'चम्मच',
    'tsp': 'चम्मच',
    'tablespoon': 'बड़ा चम्मच',
    'glass': 'गिलास',
    'glasses': 'गिलास',
    'when experiencing': 'जब हो',
    'experiencing': 'अनुभव करते समय',
    'when': 'जब',
    'heartburn': 'सीने में जलन',
    'drops': 'बूंदें',
    'pellets': 'गोलियां',
    'daily': 'रोजाना',
    'day': 'दिन',
    'days': 'दिन',
    'times': 'बार',
    'before bed': 'सोने से पहले',
    'after meals': 'खाने के बाद',
    'before meals': 'खाने से पहले',
    'morning': 'सुबह',
    'evening': 'शाम',
    'night': 'रात',
    'Drink': 'पीएं',
    'drink': 'पीएं',
    'Apply': 'लगाएं',
    'apply': 'लगाएं',
    'Take': 'लें',
    'take': 'लें',
    'Eat': 'खाएं',
    'eat': 'खाएं',
    'Avoid': 'बचें',
    'avoid': 'बचें',
    'Gargle': 'गरारे करें',
    'gargle': 'गरारे करें',
    'Rinse': 'धोएं',
    'rinse': 'धोएं',
    'Mix': 'मिलाएं',
    'mix': 'मिलाएं',
    'Boil': 'उबालें',
    'boil': 'उबालें',
    'Warm': 'गर्म करें',
    'warm': 'गर्म',
    'Soak': 'भिगोएं',
    'soak': 'भिगोएं',
    'Steep': 'डुबोएं',
    'steep': 'डुबोएं',
    'Strain': 'छानें',
    'strain': 'छानें',
    'Add': 'डालें',
    'add': 'डालें',
    'Massage': 'मालिश करें',
    'massage': 'मालिश',
    'Chew': 'चबाएं',
    'chew': 'चबाएं',
    'minutes': 'मिनट',
    'hours': 'घंटे',
    'twice': 'दो बार',
    'thrice': 'तीन बार',
    'once': 'एक बार',
    
    # Common phrases
    'black pepper': 'काली मिर्च',
    'turmeric powder': 'हल्दी पाउडर',
    'post-nasal drip': 'नाक से गले में बलगम',
    'pollution': 'प्रदूषण',
    'irritants': 'जलन पैदा करने वाले तत्व',
    'phlegm': 'बलगम',
    "Don't": 'मत',
    "don't": 'मत',
    'powder': 'पाउडर',
    'milk': 'दूध',
    
    # More common words
    'especially': 'विशेष रूप से',
    'morning and night': 'सुबह और रात',
    'clean': 'साफ',
    'fresh': 'ताज़ा',
    'small': 'छोटा',
    'piece': 'टुकड़ा',
    'every': 'हर',
    'until': 'जब तक',
    'when': 'जब',
    'while': 'करते समय',
    'use': 'उपयोग करें',
    'Use': 'उपयोग करें',
    'humidifier': 'ह्यूमिडिफायर',
    'lozenges': 'लोज़ेंजेस',
    'hard candy': 'हार्ड कैंडी',
    'liquids': 'तरल पदार्थ',
    'liquid': 'तरल',
    'suck on': 'चूसें',
    'Suck': 'चूसें',
    'Rest': 'आराम करें',
    'rest': 'आराम',
    'voice': 'आवाज',
    'utensils': 'बर्तन',
    'share': 'साझा करें',
    'soft foods': 'नरम भोजन',
    'throat': 'गला',
    'your': 'आपकी',
    'down': 'नीचे',
    'after': 'के बाद',
    'limit': 'सीमित करें',
    'Limit': 'सीमित करें',
    'Reduce': 'कम करें',
    'reduce': 'कम करें',
    'Increase': 'बढ़ाएं',
    'increase': 'बढ़ाएं',
    'lying': 'लेटना',
    'Lying': 'लेटना',
    'lying down': 'लेटना',
    'Elevate': 'ऊंचा करें',
    'elevate': 'ऊंचा',
    'elevated': 'ऊंचा',
    'head': 'सिर',
    'bed': 'बिस्तर',
    'while sleeping': 'सोते समय',
    'eating': 'खाना',
    'Sleep': 'सोएं',
    'sleep': 'नींद',
    'chew': 'चबाना',
    'Chew': 'चबाएं',
    'gum': 'च्युइंग गम',
    'Increase saliva': 'लार बढ़ाएं',
    'saliva': 'लार',
    'esophageal sphincter': 'भोजन नली की मांसपेशी',
    'Weakened lower esophageal sphincter': 'कमजोर भोजन नली की मांसपेशी',
    'Weakened': 'कमजोर',
    'weakened': 'कमजोर',
    'lower': 'निचली',
    'pregnancy': 'गर्भावस्था',
    'obesity': 'मोटापा',
    'hernia': 'हर्निया',
    'hiatal hernia': 'हायटल हर्निया',
    'Dry': 'शुष्क',
    'dry': 'शुष्क',
    'dry air': 'शुष्क हवा',
    'strain': 'तनाव',
    'voice strain': 'आवाज पर तनाव',
    'salt': 'नमक',
    'Salt': 'नमक',
    'saltwater': 'नमक का पानी',
    'Saltwater': 'नमक का पानी',
    'drinks': 'पेय पदार्थ',
    'drink': 'पेय',
    'Drink warm liquids': 'गर्म तरल पदार्थ पीएं',
    'warm liquids': 'गर्म तरल पदार्थ',
    'Eat': 'खाएं',
    'eat': 'खाएं',
    'Suck on': 'चूसें',
    'cold drinks': 'ठंडे पेय',
    'cold drink': 'ठंडा पेय',
    'Avoid cold drinks': 'ठंडे पेय से बचें',
    'Rest your voice': 'आवाज को आराम दें',
    'Gargle with': 'गरारे करें',
    'gargle with': 'गरारे करें',
    'Mix': 'मिलाएं',
    'tsp': 'चम्मच',
    'in': 'में',
    'times daily': 'बार रोजाना',
    
    # Complete phrase translations
    "Don't share utensils": 'बर्तन साझा न करें',
    "Don't smoke": 'धूम्रपान न करें',
    "Don't lie down": 'लेटें नहीं',
    "Don't pop pimples": 'मुंहासे न फोड़ें',
    "Stay well hydrated": 'पर्याप्त पानी पीएं',
    "See dentist if pain persists": 'यदि दर्द बना रहे तो दंत चिकित्सक से मिलें',
    "Avoid chewing on affected side": 'प्रभावित तरफ चबाना बंद करें',
    "Use clean towels": 'साफ तौलिए का उपयोग करें',
    "Avoid touching face frequently": 'बार-बार चेहरा छूने से बचें',
    "Change pillowcase frequently": 'तकिए का कवर बार-बार बदलें',
    "Drink plenty of water": 'पर्याप्त पानी पीएं',
    "Rinse mouth with warm saltwater": 'गर्म नमक के पानी से कुल्ला करें',
    "Avoid sugary foods": 'मीठे खाद्य पदार्थों से बचें',
    "Apply ice pack outside cheek": 'गाल के बाहर बर्फ की पट्टी लगाएं',
    "Gargle with saltwater": 'नमक के पानी से गरारे करें',
    'Painful swallowing': 'निगलने में दर्द',
    'painful swallowing': 'निगलने में दर्द',
    'swollen glands': 'सूजी हुई ग्रंथियां',
    'ice pack': 'बर्फ की पट्टी',
    
    # Individual words
    'hoarseness': 'आवाज का बैठना',
    'scratchiness': 'खरोंच',
    'swallowing': 'निगलना',
    'pillowcase': 'तकिए का कवर',
    'touching': 'छूना',
    'persists': 'बना रहे',
    'persist': 'बना रहना',
    'chewing': 'चबाना',
    'affected': 'प्रभावित',
    'dentist': 'दंत चिकित्सक',
    'outside': 'बाहर',
    'inside': 'अंदर',
    'pimples': 'मुंहासे',
    'pimple': 'मुंहासा',
    'glands': 'ग्रंथियां',
    'gland': 'ग्रंथि',
    'towels': 'तौलिए',
    'towel': 'तौलिया',
    'plenty': 'पर्याप्त',
    'sugary': 'मीठा',
    'cheek': 'गाल',
    'mouth': 'मुंह',
    'Rinse': 'कुल्ला करें',
    'rinse': 'कुल्ला',
    'side': 'तरफ',
    'face': 'चेहरा',
    'per': 'प्रति',
    'pop': 'फोड़ना',
    'See': 'मिलें',
    'see': 'मिलें',
    
    # Skin and body terms
    'Hormonal changes': 'हार्मोनल परिवर्तन',
    'hormonal changes': 'हार्मोनल परिवर्तन',
    'hormonal': 'हार्मोनल',
    'changes': 'परिवर्तन',
    'excess oil production': 'अधिक तेल उत्पादन',
    'oil production': 'तेल उत्पादन',
    'production': 'उत्पादन',
    'clogged pores': 'बंद रोम छिद्र',
    'clogged': 'बंद',
    'pores': 'रोम छिद्र',
    'non-comedogenic products': 'नॉन-कॉमेडोजेनिक उत्पाद',
    'non-comedogenic': 'नॉन-कॉमेडोजेनिक',
    'products': 'उत्पाद',
    'product': 'उत्पाद',
    'Wash face': 'चेहरा धोएं',
    'wash face': 'चेहरा धोएं',
    'Wash': 'धोएं',
    'wash': 'धोना',
    'Change pillowcase frequently': 'तकिए का कवर बार-बार बदलें',
    'change': 'बदलें',
    'Change': 'बदलें',
    'Drink plenty of water': 'पर्याप्त पानी पीएं',
    'plenty of water': 'पर्याप्त पानी',
    'plenty of': 'पर्याप्त',
    'Use non-comedogenic products': 'नॉन-कॉमेडोजेनिक उत्पाद का उपयोग करें',
    'directly on': 'सीधे',
    'directly': 'सीधे',
    'on': 'पर',
    'area': 'क्षेत्र',
    'twice': 'दो बार',
    'skin': 'त्वचा',
    'Skin': 'त्वचा',
    'clean skin': 'साफ त्वचा',
    'oily skin': 'तैलीय त्वचा',
    'oily': 'तैलीय',
    'oil': 'तेल',
    
    # Medical/Dental terms
    'oral hygiene': 'मुंह की स्वच्छता',
    'Poor oral hygiene': 'खराब मुंह की स्वच्छता',
    'poor oral hygiene': 'खराब मुंह की स्वच्छता',
    'excessive sugar intake': 'अधिक चीनी का सेवन',
    'excessive': 'अधिक',
    'sugar intake': 'चीनी का सेवन',
    'intake': 'सेवन',
    'Reduce sugar intake': 'चीनी का सेवन कम करें',
    'sugar-free': 'शुगर-फ्री',
    'dental check-ups': 'दांतों की जांच',
    'Regular dental check-ups': 'नियमित दांतों की जांच',
    'check-ups': 'जांच',
    'Brush twice daily': 'दिन में दो बार ब्रश करें',
    'Brush': 'ब्रश करें',
    'brush': 'ब्रश',
    'hygiene': 'स्वच्छता',
    'Poor': 'खराब',
    'poor': 'खराब',
    'Regular': 'नियमित',
    'regular': 'नियमित',
    'twice daily': 'दिन में दो बार',
    
    # Food and eating terms
    'Overeating': 'अधिक भोजन करना',
    'overeating': 'अधिक भोजन करना',
    'eating too fast': 'जल्दी-जल्दी खाना',
    'fatty/spicy foods': 'चिकने/मसालेदार खाद्य पदार्थ',
    'fatty foods': 'चिकने खाद्य पदार्थ',
    'spicy/oily foods': 'मसालेदार/तैलीय खाद्य पदार्थ',
    'spicy/greasy food': 'मसालेदार/चिकना भोजन',
    'greasy': 'चिकना',
    'fatty': 'चिकना',
    'fat': 'वसा',
    'meals': 'भोजन',
    'meal': 'भोजन',
    'Eat slowly': 'धीरे-धीरे खाएं',
    'eat slowly': 'धीरे-धीरे खाएं',
    'chew well': 'अच्छी तरह चबाएं',
    'Include ginger in meals': 'भोजन में अदरक शामिल करें',
    'ginger': 'अदरक',
    'Ginger': 'अदरक',
    'buttermilk': 'छाछ',
    'Buttermilk': 'छाछ',
    'carbonated drinks': 'कार्बोनेटेड पेय',
    'carbonated': 'कार्बोनेटेड',
    'Avoid carbonated drinks': 'कार्बोनेटेड पेय से बचें',
    'jeera water': 'जीरा पानी',
    'smaller portions': 'छोटे हिस्से',
    'portions': 'हिस्से',
    'cucumber': 'खीरा',
    'Include cucumber in diet': 'आहार में खीरा शामिल करें',
    'diet': 'आहार',
    'Chew food thoroughly': 'भोजन को अच्छी तरह चबाएं',
    'thoroughly': 'अच्छी तरह',
    'Eat foods to neutralize acid': 'एसिड को बेअसर करने वाले खाद्य पदार्थ खाएं',
    'foods to neutralize acid': 'एसिड को बेअसर करने वाले खाद्य पदार्थ',
    'Eat bananas to neutralize acid': 'एसिड को बेअसर करने के लिए केले खाएं',
    'bananas to neutralize acid': 'एसिड को बेअसर करने के लिए केले',
    'to neutralize acid': 'एसिड को बेअसर करने के लिए',
    'late night eating': 'देर रात खाना',
    'late night meals': 'देर रात का खाना',
    'late night': 'देर रात',
    'late': 'देर',
    'Avoid late night eating': 'देर रात खाने से बचें',
    'Avoid late night meals': 'देर रात का खाना बचें',
    'bananas': 'केले',
    'banana': 'केला',
    'Eat small frequent meals': 'छोटे-छोटे बार-बार भोजन करें',
    'small frequent meals': 'छोटे-छोटे बार-बार भोजन',
    'small': 'छोटा',
    'frequent': 'बार-बार',
    'food intolerance': 'भोजन असहिष्णुता',
    'intolerance': 'असहिष्णुता',
    'tolerant': 'सहनशील',
    'tolerate': 'सहन करना',
    'eating': 'खाना',
    'Reduce stress': 'तनाव कम करें',
    'reduce stress': 'तनाव कम करें',
    'Reduce': 'कम करें',
    'reduce': 'कम करें',
    
    # Medical conditions and terms
    'Excess stomach acid': 'पेट में अधिक एसिड',
    'excess': 'अधिक',
    'stomach acid': 'पेट का एसिड',
    'hiatal hernia': 'हायटल हर्निया',
    'certain medications': 'कुछ दवाएं',
    'medications': 'दवाएं',
    'medication': 'दवा',
    'H. pylori infection': 'एच. पाइलोरी संक्रमण',
    'H. pylori': 'एच. पाइलोरी',
    'pylori': 'पाइलोरी',
    'NSID overuse': 'NSAID का अधिक उपयोग',
    'NSAID overuse': 'NSAID का अधिक उपयोग',
    'NSAIDs': 'NSAIDs',
    'NSAID': 'NSAID',
    'overuse': 'अधिक उपयोग',
    'Avoid alcohol, NSAIDs': 'शराब, NSAIDs से बचें',
    'Avoid alcohol': 'शराब से बचें',
    'excessive alcohol': 'अधिक शराब',
    'autoimmune': 'स्वप्रतिरक्षित',
    'Autoimmune': 'स्वप्रतिरक्षित',
    'neutralize acid': 'एसिड को बेअसर करना',
    'neutralize': 'बेअसर करना',
    'Sip cold milk': 'ठंडा दूध घूंट-घूंट पीएं',
    'Sip': 'घूंट-घूंट पीएं',
    'sip': 'घूंट',
    'Include': 'शामिल करें',
    'include': 'शामिल करें',
    'Avoid': 'बचें',
    'avoid': 'बचें',
    
    # Position and posture terms
    'Stay upright after meals': 'खाने के बाद सीधे रहें',
    'Stay upright': 'सीधे रहें',
    'upright': 'सीधे',
    'Eat slowly and chew well': 'धीरे-धीरे खाएं और अच्छी तरह चबाएं',
    "Don't lie down immediately after eating": 'खाने के तुरंत बाद न लेटें',
    'immediately': 'तुरंत',
    'immediately after': 'तुरंत बाद',
    
    # Common phrases
    'Stay hydrated': 'पर्याप्त पानी पीएं',
    'Rest well': 'अच्छा आराम करें',
    'Consult doctor': 'डॉक्टर से परामर्श लें',
    'See dentist': 'दंत चिकित्सक से मिलें',
    'if needed': 'यदि आवश्यक हो',
    'as needed': 'आवश्यकतानुसार',
    'or until': 'या जब तक',
    'Continue for': 'जारी रखें',
    'Repeat': 'दोहराएं',
    'fresh': 'ताज़ा',
    'clean': 'साफ',
    'affected area': 'प्रभावित क्षेत्र',
    'affected tooth': 'प्रभावित दांत',
    
    # Medical terms
    'infection': 'संक्रमण',
    'inflammation': 'सूजन',
    'bacteria': 'बैक्टीरिया',
    'viral': 'वायरल',
    'bacterial': 'बैक्टीरियल',
    'allergies': 'एलर्जी',
    'stress': 'तनाव',
    'dehydration': 'पानी की कमी',
    'immunity': 'प्रतिरक्षा',
    'digestion': 'पाचन',
    'acid': 'एसिड',
    'pain': 'दर्द',
    'relief': 'राहत',
    'treatment': 'उपचार',
    'symptoms': 'लक्षण',
    'spicy': 'मसालेदार',
    'oily': 'तैलीय',
    'fried': 'तला हुआ',
    'cold': 'ठंडा',
    'hot': 'गर्म',
    'foods': 'खाद्य पदार्थ',
    'food': 'भोजन',
    'foods to': 'खाद्य पदार्थ जो',
    'Eat foods': 'खाद्य पदार्थ खाएं',
    'smoke': 'धूम्रपान',
    'smoking': 'धूम्रपान',
    'alcohol': 'शराब',
    'caffeine': 'कैफीन',
    'tobacco': 'तंबाकू',
    'sugar': 'चीनी',
    'dairy': 'दुग्ध उत्पाद',
    'plain': 'सादा',
    'Plain': 'सादा',
    'without': 'बिना',
    'without sugar': 'बिना चीनी',
    
    # Common English words
    'for': 'के लिए',
    'with': 'के साथ',
    'and': 'और',
    'or': 'या',
    'of': 'का',
    'in': 'में',
    'on': 'पर',
    'to': 'को',
    'at': 'पर',
    'from': 'से',
    'if': 'अगर',
    'you': 'आप',
    'have': 'हैं',
    'the': '',
    'a': '',
    'an': '',
    'is': 'है',
    'are': 'हैं',
    'be': 'होना',
    'frequently': 'बार-बार',
    'regularly': 'नियमित रूप से',
    'gently': 'धीरे से',
    'slowly': 'धीरे-धीरे',
    'properly': 'ठीक से',
    'well': 'अच्छी तरह',
    'immediately': 'तुरंत',
    'daily': 'रोजाना',
    'weekly': 'साप्ताहिक',
    'monthly': 'मासिक',
    
    # Common phrases
    'black pepper': 'काली मिर्च',
    'turmeric powder': 'हल्दी पाउडर',
    'post-nasal drip': 'नाक से गले में बलगम',
    'pollution': 'प्रदूषण',
    'irritants': 'जलन पैदा करने वाले तत्व',
    'phlegm': 'बलगम',
    "Don't": 'मत',
    "don't": 'मत',
    'powder': 'पाउडर',
    'milk': 'दूध',
}

def translate_to_hindi_content(text, lang='en'):
    """
    Translate content to Hindi when language is 'hi'
    Uses word-by-word replacement for comprehensive translation
    """
    if not text or lang != 'hi':
        return text
    
    if text == 'Not specified':
        return 'निर्दिष्ट नहीं'
    
    result = text
    
    # Sort by length (descending) to replace longer phrases first
    sorted_translations = sorted(CONTENT_TRANSLATIONS.items(), key=lambda x: len(x[0]), reverse=True)
    
    for eng, hindi in sorted_translations:
        # Case-insensitive replacement
        import re
        pattern = re.compile(re.escape(eng), re.IGNORECASE)
        result = pattern.sub(hindi, result)
    
    return result

def translate_disease_name(disease, lang='en'):
    """Translate disease name to Hindi"""
    if lang != 'hi':
        return disease
    return CONTENT_TRANSLATIONS.get(disease, disease)

def translate_to_hindi_complete(text):
    """Complete Hindi translation for all text (backward compatibility)"""
    if not text or text == 'Not specified':
        return 'निर्दिष्ट नहीं'
    
    translations = {
        'fever': 'बुखार', 'headache': 'सिरदर्द', 'cough': 'खांसी', 'cold': 'जुकाम',
        'stomach pain': 'पेट दर्द', 'body ache': 'शरीर दर्द', 'nausea': 'मतली',
        'tablet': 'गोली', 'medicine': 'दवा', 'take': 'लें', 'times': 'बार',
        'morning': 'सुबह', 'evening': 'शाम', 'water': 'पानी', 'honey': 'शहद',
        'Common Cold': 'सामान्य जुकाम', 'Fever': 'बुखार', 'Headache': 'सिरदर्द',
        'Cough': 'खांसी', 'Stomach Pain': 'पेट दर्द', 'Body Ache': 'शरीर दर्द',
        'Acidity': 'अम्लता', 'Constipation': 'कब्ज', 'Diarrhea': 'दस्त',
        'Indigestion': 'अपच', 'Nausea': 'मतली', 'Vomiting': 'उल्टी',
        'Joint Pain': 'जोड़ों का दर्द', 'Back Pain': 'कमर दर्द',
        'Sore Throat': 'गले में दर्द', 'Skin Problems': 'त्वचा की समस्याएं',
        'Allergies': 'एलर्जी', 'Asthma': 'दमा', 'Diabetes': 'मधुमेह',
        'Hypertension': 'उच्च रक्तचाप', 'Anxiety': 'चिंता', 'Depression': 'अवसाद',
        'Insomnia': 'अनिद्रा', 'Fatigue': 'थकान', 'Weakness': 'कमजोरी'
    }
    
    result = text
    for eng, hindi in translations.items():
        result = result.replace(eng, hindi)
    return result